name: Check Bayern Match

on:
  schedule:
    # Запуск щодня об 11:00 UTC (це 13:00 за київським часом або 12:00 за центральноєвропейським CEST)
    - cron: '0 11 * * *'
  # Дозволяє запускати перевірку вручну кнопкою для тесту
  workflow_dispatch:

jobs:
  check-match:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
        run: python main.py
